'use strict';

const nodemailer = require('nodemailer');

function createTransporter() {
  return nodemailer.createTransport({
    host:   process.env.SMTP_HOST,
    port:   parseInt(process.env.SMTP_PORT || '587', 10),
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });
}

function buildPlainText(report, transcript) {
  const topics = report.topicsDiscussed?.length
    ? report.topicsDiscussed.map((t) => `  • ${t}`).join('\n')
    : '  None reported';

  const followUp = report.followUpActions?.length
    ? report.followUpActions.map((f) => `  → ${f}`).join('\n')
    : '  None';

  const incidents = report.incidentsOrIssues?.length
    ? report.incidentsOrIssues.map((i) => `  ⚠ ${i}`).join('\n')
    : '  None';

  return [
    'LORETRACK — GBR ENGAGEMENT REPORT',
    '══════════════════════════════════════════',
    `Lead:              ${report.workerName || 'Unknown'}`,
    `Date:              ${report.date || 'Unknown'}`,
    `Region:            ${report.region || '—'}`,
    `TO Group:          ${report.toGroup || '—'}`,
    `Engagement Type:   ${report.engagementType || '—'}`,
    `Attendees:         ${report.attendees || '—'}`,
    '',
    'TOPICS DISCUSSED',
    topics,
    '',
    'CONSENT STATUS',
    `  Status:  ${report.consentStatus || '—'}`,
    ...(report.consentNotes ? [`  Notes:   ${report.consentNotes}`] : []),
    '',
    'FOLLOW-UP ACTIONS',
    followUp,
    ...(report.nextContact ? ['', `NEXT CONTACT:  ${report.nextContact}`] : []),
    ...(report.culturalProtocolNotes ? ['', 'CULTURAL PROTOCOL NOTES', `  ${report.culturalProtocolNotes}`] : []),
    ...(incidents !== '  None' ? ['', 'INCIDENTS / ISSUES', incidents] : []),
    ...(report.additionalNotes ? ['', 'ADDITIONAL NOTES', `  ${report.additionalNotes}`] : []),
    '',
    '──────────────────────────────────────────',
    'ORIGINAL TRANSCRIPT',
    transcript,
    '══════════════════════════════════════════',
    'Generated by LoreTrack — GBR Engagement Reporting | Nirrwara Global',
  ].join('\n');
}

function buildHtml(report, transcript) {
  const topicItems = report.topicsDiscussed?.length
    ? report.topicsDiscussed.map((t) => `<li>${esc(t)}</li>`).join('')
    : '<li><em>None reported</em></li>';

  const followUpItems = report.followUpActions?.length
    ? report.followUpActions.map((f) => `<li>→ ${esc(f)}</li>`).join('')
    : '<li><em>None</em></li>';

  const incidentItems = report.incidentsOrIssues?.length
    ? report.incidentsOrIssues.map((i) => `<li style="color:#922B21">⚠ ${esc(i)}</li>`).join('')
    : null;

  const consentColour = {
    'Consented':           '#1a7a4a',
    'In deliberation':     '#b45309',
    'Declined':            '#922B21',
    'Withdrawn':           '#922B21',
    'Initial contact made':'#1B3A4B',
    'Not yet approached':  '#6B6B6B',
  }[report.consentStatus] || '#1B3A4B';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  body{font-family:Arial,sans-serif;max-width:640px;margin:0 auto;padding:24px;color:#1A1A1A;background:#F5F0E8}
  .card{background:#fff;border-radius:12px;padding:24px;margin-bottom:16px;border:1px solid #DDD5C4}
  h1{background:#1B3A4B;color:#fff;padding:16px 22px;border-radius:10px;font-size:20px;margin:0 0 16px}
  .program-tag{background:#2E75B6;color:#fff;font-size:11px;padding:3px 10px;border-radius:20px;display:inline-block;margin-bottom:16px;letter-spacing:.5px}
  h2{font-size:12px;text-transform:uppercase;letter-spacing:.8px;color:#6B6B6B;margin:0 0 10px}
  dl{display:grid;grid-template-columns:1fr 1fr;gap:4px 12px}
  dt{font-size:13px;color:#6B6B6B}
  dd{font-size:15px;font-weight:600;margin:0}
  ul{padding-left:20px;margin:0}
  li{margin:4px 0;font-size:15px}
  .consent-badge{display:inline-block;padding:4px 14px;border-radius:20px;font-weight:700;font-size:14px;color:#fff;background:${consentColour}}
  .transcript{background:#F9F9F9;border-left:4px solid #1B3A4B;padding:14px;font-style:italic;font-size:14px;border-radius:0 8px 8px 0}
  .footer{text-align:center;font-size:12px;color:#999;margin-top:20px}
  .cultural-note{background:#FFF8E7;border-left:4px solid #C9A96E;padding:12px 14px;border-radius:0 8px 8px 0;font-size:14px}
</style>
</head>
<body>
<h1>🌿 LoreTrack Engagement Report</h1>
<div class="program-tag">GBR Traditional Owner-Led Water Quality Improvement Program</div>

<div class="card">
  <h2>Engagement Details</h2>
  <dl>
    <dt>Regional Lead</dt><dd>${esc(report.workerName || '—')}</dd>
    <dt>Date</dt><dd>${esc(report.date || '—')}</dd>
    <dt>Region</dt><dd>${esc(report.region || '—')}</dd>
    <dt>TO Group</dt><dd>${esc(report.toGroup || '—')}</dd>
    <dt>Engagement Type</dt><dd>${esc(report.engagementType || '—')}</dd>
    <dt>Attendees</dt><dd>${esc(report.attendees || '—')}</dd>
  </dl>
</div>

<div class="card">
  <h2>Topics Discussed</h2>
  <ul>${topicItems}</ul>
</div>

<div class="card">
  <h2>Consent Status</h2>
  <p><span class="consent-badge">${esc(report.consentStatus || 'Not recorded')}</span></p>
  ${report.consentNotes ? `<p style="font-size:14px;margin-top:8px;color:#444">${esc(report.consentNotes)}</p>` : ''}
</div>

${report.culturalProtocolNotes ? `
<div class="card">
  <h2>Cultural Protocol Notes</h2>
  <div class="cultural-note">${esc(report.culturalProtocolNotes)}</div>
</div>` : ''}

<div class="card">
  <h2>Follow-Up Actions</h2>
  <ul>${followUpItems}</ul>
  ${report.nextContact ? `<p style="font-size:13px;color:#6B6B6B;margin-top:12px">📅 Next contact: <strong>${esc(report.nextContact)}</strong></p>` : ''}
</div>

${incidentItems ? `<div class="card"><h2>Incidents / Issues</h2><ul>${incidentItems}</ul></div>` : ''}
${report.additionalNotes ? `<div class="card"><h2>Additional Notes</h2><p style="font-size:15px">${esc(report.additionalNotes)}</p></div>` : ''}

<div class="card">
  <h2>Original Transcript</h2>
  <div class="transcript">${esc(transcript)}</div>
</div>

<div class="footer">Generated by LoreTrack — GBR Engagement Reporting | Nirrwara Global / TerreIntelligence</div>
</body>
</html>`;
}

function esc(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

async function sendReport(report, supervisorEmail, transcript) {
  const transporter = createTransporter();
  const from = process.env.SMTP_FROM || process.env.SMTP_USER;
  const workerName = report.workerName || 'Regional Engagement Lead';
  const date = report.date || new Date().toLocaleDateString('en-AU');
  const toGroup = report.toGroup ? ` — ${report.toGroup}` : '';

  await transporter.sendMail({
    from,
    to: supervisorEmail,
    subject: `LoreTrack GBR: ${workerName}${toGroup} – ${date}`,
    text: buildPlainText(report, transcript),
    html: buildHtml(report, transcript),
  });
}

module.exports = { sendReport };